### ISSUE TITLE
cool code pls add

### ISSUE THREAD

**Issue by GnomeDevs** [axolib/Axolotl-Library#3]
:ha::arrow_forward: :filterfurry::arrow_backward: :arrow_down_small: 
:furrysquish:
:ha::arrow_double_down: 
:furrysad: :ferrystop: 
:arrow_double_up:

![image](https://user-images.githubusercontent.com/73052469/105664387-7f4f8c80-5f0f-11eb-994e-bb1aa694e798.png)

**Comment by axolib** [comment]
shitting bricks rn

**Comment by Dvd-22** [comment]
Add it rn
